$40010000 constant SYSCFG_COMP_BASE

SYSCFG_COMP_BASE $00 + constant SYSCFG_CFGR1
SYSCFG_COMP_BASE $04 + constant SYSCFG_CFGR2
SYSCFG_COMP_BASE $08 + constant SYSCFG_EXTICR1
SYSCFG_COMP_BASE $0C + constant SYSCFG_EXTICR2
SYSCFG_COMP_BASE $10 + constant SYSCFG_EXTICR3
SYSCFG_COMP_BASE $14 + constant SYSCFG_EXTICR4
SYSCFG_COMP_BASE $20 + constant SYSCFG_CFGR3
