$40010000 constant AFIO_BASE

AFIO_BASE $00 + constant AFIO_EVCR
AFIO_BASE $04 + constant AFIO_MAPR
AFIO_BASE $08 + constant AFIO_EXTICR1
AFIO_BASE $0C + constant AFIO_EXTICR2
AFIO_BASE $10 + constant AFIO_EXTICR3
AFIO_BASE $14 + constant AFIO_EXTICR4
AFIO_BASE $1C + constant AFIO_MAPR2
